/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Tachyon {
  constructor()
  get(route: string, handler: (request: TachyonRequest, response: TachyonResponse) => void): void
  routes(): Array<string>
  listen(port: number): Promise<void>
}

export declare class TachyonRequest {

}

export declare class TachyonResponse {

}

export declare function tachyon(): Tachyon
