/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ResponseHandle {
  id: number
  constructor(id: number)
  send(data: any): void
}

export declare class Tachyon {
  constructor()
  get(route: string, callback: any): void
  routes(): Array<string>
  listen(port: number): Promise<void>
}

export declare class TachyonRequest {
  constructor()
}

export declare class TachyonResponse {
  constructor()
  send(value: any): void
}

export declare function tachyon(): Tachyon
